### ISSUE TITLE
Improve instructions to set up environment

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-maintenance-scripts#126]
including git clone, etc.

Also, show examples of test results, and how to read the results.

Can also consider Vagrant to ease setup.

**Comment by jpmckinney** [comment]
cc @odscjames

**Comment by odscjames** [comment]
(Other technologies such as Docker are available - the point is to script setting up an environment to make it easy for people to get started, and to get the latest updates. And something in a virtual environment of some sort, so it can be installed on varied machines without having to worry about conflicts with existing software.)

**Comment by jpmckinney** [comment]
This hasn't come up as an issue again, so closing.
