### ISSUE TITLE
Build failing: An error occurred while installing mdl (0.5.0), and Bundler cannot continue.

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard-maintenance-scripts#138]
The OC for Infrastructure build is failing with the above error.

Here's an example of a build which ran successfully a couple of days ago and failed today when I restarted it (there were no changes on the master branch between the builds): https://travis-ci.org/open-contracting/infrastructure/builds/468946810

**Comment by duncandewhurst** [comment]
Noting the main standard build is also failing on the same error: https://travis-ci.org/open-contracting/standard/builds/470069075

**Comment by jpmckinney** [comment]
Fixed in https://github.com/open-contracting/standard-maintenance-scripts/commit/4ceeb358c32b8acae0b96f8da66c912fb67a2518
