### ISSUE TITLE
Consider replacing `cld2` with `cld3` in Gemfile

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/standard-maintenance-scripts#159]
Running `bundle` with the current Gemfile fails at installing `cld2` on Ubuntu 20.04 (a popular OS). If feasible we should consider replacing it with `cld3` as the former is no longer maintained while the [latter is](https://rubygems.org/gems/cld3).

There were still issues with installing `cld3` in Ubuntu 20.04 as it requires an install of [protobuf](https://github.com/protocolbuffers/protobuf) to work.

**Comment by jpmckinney** [comment]
Hmm, cld3 requires ffi, which leads down a huge rabbit hole on macOS at least: https://github.com/ffi/ffi/issues/653

I'll update the readme to make clear that Ruby is only required for some tasks (that only I perform).

**Comment by jpmckinney** [comment]
Ah, I see the Rake task that was mentioned in the process note. I've now instead suggested to do those steps manually (checking language and length). I've made cld optional in the repo, since it's only used by the documentation_language_length task.
