### ISSUE TITLE
test_json.py: Ensure `openCodelist: false` sets `enum`

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-maintenance-scripts#16]
* [x] Ensure `enum` is set if `openCodelist` is `false`, blocked open-contracting/ocds-extensions#32
* [x] Ensure `enum` is not set if `openCodelist` is `true`
* [x] Check that `enum` matches `codelist` codes
* [x] Ensure codelist fields are set if `enum` is set, blocked https://github.com/open-contracting/ocds-extensions/issues/43

**Comment by jpmckinney** [comment]
Must close https://github.com/open-contracting/ocds-extensions/issues/32 before uncommenting the call to the new method for checking codelists in schema.

**Comment by jpmckinney** [comment]
Write `fix:codelist` task to set and update `enum` if `openCodelist` is `false`, and then run it on all of https://github.com/open-contracting/ocds-extensions/issues/32

**Comment by timgdavies** [comment]
* [ ] Check that codelist enum values contain a `null` option

I think we need the above to [make sure that it is possible to unset values in later releases](http://standard.open-contracting.org/latest/en/schema/reference/#emptying-fields-and-values). 

In the [main schema](https://github.com/open-contracting/standard/blob/1.1-dev/standard/schema/release-schema.json) we have `null` as an option for all except `release.tag` and `release.initiationType`.

**Comment by jpmckinney** [comment]
Note to myself to check whether the code handles the case where both `type` and `items` are set (e.g. in geometry where there is an array of numbers or arrays.

**Comment by jpmckinney** [comment]
> Check that codelist enum values contain a null option

Already done at https://github.com/open-contracting/standard-maintenance-scripts/blob/master/tests/test_json.py#L336-L338

I tested with an extension by removing `null` from the `enum` and I got a failure. Let me know if you saw different behaviour.

**Comment by jpmckinney** [comment]
> Note to myself to check whether the code handles the case where both `type` and `items` are set (e.g. in geometry where there is an array of numbers or arrays).

Not sure what I meant by that, as not relevant to `enum` or codelists. If my comment was about the inclusion of `"null"`  in `type`, that's handled regardless of `items`. I may want to add a check that `null` is not an allowed `type` within `items`.

I added a TODO using the schema from 1.1.3-dev, which can be removed once 1.1.3 is released.
