### ISSUE TITLE
Can Gemfile.lock be edited to support multiple Bundler versions?

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/standard-maintenance-scripts#160]
The `Gemfile.lock` requires the version of Bundler to be `1.16.2` while contemporary version on disto repos is `2.1.4`. This causes an error when setting up. Deleting the `Gemfile.lock` allows `bundle` to run, although obviously now there might be newer versions of libraries installed.

I'm familiar with .lock files from Composer but Composer didn't version lock the version of itself required to run with the lock file (to my knowledge). Can `Gemfile.lock` be edited to remove the Bundler version requirement safely?

**Comment by jpmckinney** [comment]
I've now removed Gemfile.lock from revision control.
