### ISSUE TITLE
Document periodic Markdown lint process

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-maintenance-scripts#26]
https://github.com/open-contracting/standard-maintenance-scripts/pull/25

It's possible to configure text editors to visually communicate Markdown warnings (much like how spelling errors are visually communicated in word processors).

Markdownlint can be configured to ignore specific Markdown warnings (it already ignores three kinds); we can discuss which to add to that list.

* [x] [Configure](https://github.com/markdownlint/markdownlint/blob/25081c5b1a1312a111d22791197e6e2ad8092a0c/test/rule_tests/header_trailing_punctuation_customized_style.rb) MD026 (Trailing punctuation in header) to allow headers to end with a question mark (e.g. in an FAQ). [Documentation](https://github.com/markdownlint/markdownlint/blob/25081c5b1a1312a111d22791197e6e2ad8092a0c/docs/RULES.md#md026---trailing-punctuation-in-header)
* [x] Document how to run Markdown linting across a directory containing repositories

**Comment by jpmckinney** [comment]
Assigning @Bjwebb @timgdavies as they authored/merged the change to Markdown warnings.

**Comment by timgdavies** [comment]
My experience authoring is that too much linting at the wrong moment can disrupt the drafting process.

It's useful to be able to make quick edits, and preview. 

I couldn't find good docs that would help me run all the tests locally, before pushing - and although I tried for the best part of an hour to set-up markdown linting for my editor to match the rules being applied - in the end had to just crack on the writing.

My preference would be for us to find an approach that can **report** on quality of the markdown, but not turn it into a blocker for building development branches. E.g. a badge to show us that we're 97% good markdown - that we would pay particular attention to when preparing for a deployment.

**Comment by jpmckinney** [comment]
Storing old configuration here:

```
curl -s -S -o /tmp/mdlrc.rb $BASEDIR/fixtures/mdlrc.rb
/tmp/bin/mdl --git-recurse --style /tmp/mdlrc.rb .
```

mdlrc.rb:

```ruby
all

# Rules can be configured. See https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

# See https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md026---trailing-punctuation-in-header
rule 'MD026', :punctuation => '.,;:!'

exclude_rule 'MD009' # Trailing spaces (common error frustrates users)
exclude_rule 'MD013' # Line length (breaking lines in paragraphs produces longer diffs)
exclude_rule 'MD024' # Multiple headers with the same content (bug https://github.com/markdownlint/markdownlint/issues/175)
exclude_rule 'MD033' # Inline HTML (some files require HTML)
```
