### ISSUE TITLE
markdownlint installation fails

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard-maintenance-scripts#30]
https://travis-ci.org/open-contracting/extension_tester/jobs/297635460

**Comment by jpmckinney** [comment]
Comparing the log to one of a successful build 3 days ago, there's no difference except irrelevant stuff (different extensions, on different Travis servers, at different times). Markdownlint and its dependencies have not changed in that time period. Hard to know what the issue is.

**Comment by jpmckinney** [comment]
Bundler 1.6.0 and RubyGems 2.7.0 and 2.7.1 were released in the last week and caused the error (mysteriously).
