### ISSUE TITLE
test_json.py: Test extensions against extension-schema.json

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-maintenance-scripts#33]
https://github.com/open-contracting/standard_extension_template/blob/master/schema/extension-schema.json

We can consider moving that schema out of that repository, as it shouldn't be distributed with extensions.

**Comment by jpmckinney** [comment]
Must merge all above PRs on extensions, and then #34

**Comment by jpmckinney** [comment]
@timgdavies Is there any reason not to update the extension.json files to the schema documented in extension-schema.json?

**Comment by jpmckinney** [comment]
I looked for all mentions of `extension.json`, and as far as I can tell, nothing is disturbed by this change. Most code only reads from the registry. The only new data in `extension.json` is the `codelists` array, which is unchanged by these PRs.

**Comment by jpmckinney** [comment]
@edugomez I created PRs to update the extension.json files in all extensions to validate against extension-schema.json. Will anything break if I merge the PRs?

**Comment by edugomez** [comment]
@jpmckinney, it should be OK. I _think_ the only tool we currently have that extends the schema is Cove, for which we already have a bit of code for changes in _extension.json_ files:

https://github.com/OpenDataServices/cove/blob/master/cove_ocds/lib/schema.py#L149

Standard docs use the information in the registry, so they should be OK too. But let me know if you want me to go over our repos and double check that everything is OK with those merges.

**Comment by jpmckinney** [comment]
I think the merges will be safe, and I think the only remaining code that uses the old format is the extension creator, for which I created an issue https://github.com/open-contracting/extension_creator/issues/9

**Comment by jpmckinney** [comment]
FYI, I documented what depends on `extension-schema.json` here: https://github.com/open-contracting/standard-maintenance-scripts#extension-schemajson
