### ISSUE TITLE
extension_registry entry-schema.json fails tests

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard-maintenance-scripts#59]
[extension_registry entry-schema.json](https://github.com/open-contracting/extension_registry/blob/master/entry-schema.json) [fails tests](https://travis-ci.org/open-contracting/extension_registry/builds/323110850).

This is due to this validation function:

https://github.com/open-contracting/standard-maintenance-scripts/blob/32097d90c1d1abf7f93c3263a2b488359a8a82d0/tests/test_json.py#L392-L405

As I understand it, the options are:
* Move /items into a definition, and ref to it (although this seems somewhat unnecessary for this case)
* Add an exception

**Comment by Bjwebb** [comment]
@jpmckinney What do you think to adding an exception for this?

**Comment by jpmckinney** [comment]
I added an exception, and build passed now :)
