### ISSUE TITLE
script.sh: CSV and codelist testing

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-maintenance-scripts#6]
CSVs exist in (at least):

* codelist files
* `sample-data/flat-template/template`
* `standard/standard/docs/en/examples`

We can write a pytest and add it to `script.sh` that:

* [x] Checks CSV formatting with standard options
  * Basically, read it into Python, check for whitespace at the start/end of values (especially codes), check for empty rows/columns, write it back out with standard options (i.e. utf-8 encoding, `,` field delimiter, `\n` line terminator, `"` escape character), and compare whether the input matches the output
* [x] Checks CSV headers for codelists (Code, Title, Description) e.g. https://github.com/open-contracting/ocds-extensions/issues/24
* [ ] Unflattens CSVs and validates against JSON Schema

An example CSV with an uneven number of columns (which prevents rendering as a table on GitHub) is https://github.com/open-contracting/ocds_requirements_extension/blob/master/codelists/relatesTo.csv

**Comment by robredpath** [comment]
@jpmckinney is it worth using CoVE for this? There's a cmdline version for OCDS now which could help make sure that we're giving consistent results across validators and deal with the grunt work of this functionality
